options {
    directory "/var/cache/bind";
    session-keyfile "/var/cache/bind/session.key";

    listen-on port 53 { any; };
    listen-on-v6 { none; };

    recursion no;
    allow-query { any; };
    dnssec-validation no;
};

zone "bank.test" IN {
    type master;
    file "/etc/bind/bank.test.zone";
    allow-query { any; };
};
